import type { APIRoute } from 'astro';
import { json, refusal, requireOwner } from '../../../lib/authorize';

/**
 * The authoring assistant's conversations: list, read, append, delete.
 *
 * ## Why this is not `POST /api/content`
 *
 * Every other write on this site goes through one endpoint and one tested
 * column allowlist, and that rule is worth keeping — but the reason for it is
 * specific. `/api/content` exists because **a table or column name cannot be a
 * bound parameter**, so the identifiers in a statement have to come from source
 * rather than from a request, and concentrating that in one place makes it one
 * thing to test rather than one per feature.
 *
 * Nothing here takes an identifier from a caller. Every statement below is
 * written out in full with `?` placeholders; there is no map to look a column
 * up in, because there is no caller-supplied key to look up. What this route
 * needs that the generic one cannot give is an **append** — `ai_messages` has
 * an autoincrementing id and no slug, and the generic endpoint is a slug-keyed
 * upsert. Bending it into an insert-only shape for one table would put a second
 * mode in the endpoint whose whole value is having one.
 *
 * So: fixed SQL, owner-only, and the same refusal path as everywhere else.
 *
 * ## Caps
 *
 * A message is capped at 20,000 characters and a transcript at 400 messages,
 * both silently. This is a private table written by one person's browser, so
 * the caps are here to bound a runaway loop rather than to police anyone —
 * a streaming reply that never terminates would otherwise write until D1 said
 * no, and D1 saying no mid-conversation is a worse failure than a truncated
 * message.
 */

export const prerender = false;

const MAX_CONTENT = 20_000;
const MAX_THINKING = 20_000;
const MAX_TITLE = 120;
/** Enough that nobody meets it by writing; low enough that a loop stops. */
const MAX_MESSAGES = 400;
/** The history list. Older conversations are still readable by id. */
const MAX_CHATS = 60;

const text = (value: unknown, limit: number): string =>
  typeof value === 'string' ? value.slice(0, limit) : '';

/** Opaque, and generated by the browser. Pinned to a shape so it cannot be a path. */
const ID = /^[a-z0-9-]{6,64}$/;

interface ChatRow {
  id: string;
  surface: string;
  doc_slug: string | null;
  title: string;
  created_at: string;
  updated_at: string;
}

interface MessageRow {
  id: number;
  role: string;
  content: string;
  thinking: string | null;
  task: string | null;
  created_at: string;
}

export const GET: APIRoute = async ({ request, locals }) => {
  try {
    await requireOwner(request);
  } catch (error) {
    return refusal(error) ?? json({ error: 'Unauthorized.' }, 401);
  }

  const { DB } = locals.runtime.env;
  const url = new URL(request.url);
  const id = url.searchParams.get('id');

  if (id) {
    if (!ID.test(id)) return json({ error: 'Not a conversation id.' }, 400);
    const chat = await DB.prepare('SELECT * FROM ai_chats WHERE id = ?').bind(id).first<ChatRow>();
    if (!chat) return json({ error: 'No such conversation.' }, 404);
    const { results } = await DB.prepare(
      'SELECT id, role, content, thinking, task, created_at FROM ai_messages WHERE chat_id = ? ORDER BY id ASC',
    )
      .bind(id)
      .all<MessageRow>();
    return json({ chat, messages: results ?? [] });
  }

  /* The list, per surface. A journal conversation offered in the project editor
     would be history that cannot be continued where it is shown. */
  const surface = url.searchParams.get('surface') === 'project' ? 'project' : 'journal';
  const { results } = await DB.prepare(
    `SELECT c.*, (SELECT COUNT(*) FROM ai_messages m WHERE m.chat_id = c.id) AS messages
       FROM ai_chats c
      WHERE c.surface = ?
      ORDER BY c.updated_at DESC
      LIMIT ?`,
  )
    .bind(surface, MAX_CHATS)
    .all<ChatRow & { messages: number }>();

  return json({ chats: results ?? [] });
};

interface Body {
  op?: string;
  id?: string;
  surface?: string;
  docSlug?: string;
  title?: string;
  role?: string;
  content?: string;
  thinking?: string;
  task?: string;
  /** `compact` replaces the transcript with this one summary. */
  summary?: string;
}

export const POST: APIRoute = async ({ request, locals }) => {
  try {
    await requireOwner(request);
  } catch (error) {
    return refusal(error) ?? json({ error: 'Unauthorized.' }, 401);
  }

  const { DB } = locals.runtime.env;
  const body = (await request.json().catch(() => ({}))) as Body;
  const id = typeof body.id === 'string' ? body.id : '';
  if (!ID.test(id)) return json({ error: 'Not a conversation id.' }, 400);

  const touch = () => DB.prepare("UPDATE ai_chats SET updated_at = datetime('now') WHERE id = ?").bind(id);

  switch (body.op) {
    case 'create': {
      const surface = body.surface === 'project' ? 'project' : 'journal';
      await DB.prepare(
        'INSERT OR IGNORE INTO ai_chats (id, surface, doc_slug, title) VALUES (?, ?, ?, ?)',
      )
        .bind(id, surface, text(body.docSlug, 120) || null, text(body.title, MAX_TITLE) || 'New conversation')
        .run();
      return json({ ok: true, id });
    }

    case 'append': {
      const role = body.role === 'assistant' || body.role === 'note' ? body.role : 'user';
      const content = text(body.content, MAX_CONTENT);
      const thinking = text(body.thinking, MAX_THINKING);
      if (!content.trim() && !thinking.trim()) return json({ ok: true, skipped: true });

      /* Counted before the insert rather than trimmed after it: a transcript
         that is already at the cap should stop growing, not lose its opening —
         which is the part a compaction is built from. */
      const count = await DB.prepare('SELECT COUNT(*) AS n FROM ai_messages WHERE chat_id = ?')
        .bind(id)
        .first<{ n: number }>();
      if ((count?.n ?? 0) >= MAX_MESSAGES) {
        return json({ error: 'This conversation is full. Compact it or start a new one.' }, 409);
      }

      const inserted = await DB.prepare(
        'INSERT INTO ai_messages (chat_id, role, content, thinking, task) VALUES (?, ?, ?, ?, ?)',
      )
        .bind(id, role, content, thinking || null, text(body.task, 60) || null)
        .run();

      await touch().run();
      return json({ ok: true, id: inserted.meta?.last_row_id ?? null });
    }

    case 'rename': {
      const title = text(body.title, MAX_TITLE).trim();
      if (!title) return json({ error: 'A conversation needs a name.' }, 400);
      await DB.prepare("UPDATE ai_chats SET title = ?, updated_at = datetime('now') WHERE id = ?")
        .bind(title, id)
        .run();
      return json({ ok: true });
    }

    case 'compact': {
      /* The summary is the model's, written by the panel before this is called.
         Replacing the transcript with it is the whole operation: the point of
         compacting is that the next request carries one paragraph instead of
         forty messages, and keeping the originals "just in case" would mean it
         carried both. It is destructive, it says so on the button, and the
         summary is inserted before the delete so a failure between the two
         leaves a transcript with a summary at the end rather than nothing. */
      const summary = text(body.summary, MAX_CONTENT).trim();
      if (!summary) return json({ error: 'Nothing to compact into.' }, 400);

      const marker = await DB.prepare(
        "INSERT INTO ai_messages (chat_id, role, content, task) VALUES (?, 'note', ?, 'compact')",
      )
        .bind(id, summary)
        .run();

      await DB.prepare('DELETE FROM ai_messages WHERE chat_id = ? AND id < ?')
        .bind(id, marker.meta?.last_row_id ?? 0)
        .run();
      await touch().run();
      return json({ ok: true });
    }

    case 'delete': {
      /* Messages first and by hand. The foreign key declares `ON DELETE
         CASCADE`, but that only fires while `PRAGMA foreign_keys` is on, and a
         transcript orphaned by a pragma being off is invisible rows nobody will
         ever look for. Two statements is cheaper than that being true. */
      await DB.prepare('DELETE FROM ai_messages WHERE chat_id = ?').bind(id).run();
      await DB.prepare('DELETE FROM ai_chats WHERE id = ?').bind(id).run();
      return json({ ok: true });
    }

    default:
      return json({ error: 'Unknown operation.' }, 400);
  }
};
