-- Generated by `npm run seed:d1` from src/content/. Do not hand-edit:
-- regenerate it, or change the row in D1, which is the source of truth
-- once this has been applied.

PRAGMA foreign_keys = ON;

-- Case studies first: `projects.case_study_slug` is a foreign key into this
-- table, so a project inserted before its case study would be refused.
INSERT INTO case_studies (slug, title, subtitle, hero_image, hero_video, problem, solution,
  architecture_image, achievements, stack, repo_url, demo_url, date, read_time, body_md, body_html)
VALUES ('axcad', 'AXCAD', 'Browser-based CAD workspace with parametric constraints, command workflows, and export pipelines.', NULL, NULL,
  'Most lightweight web drawing tools are not suitable for precision drafting workflows because they lack command-driven editing, constraints, and production-ready export formats.', 'Built a TypeScript/React CAD editor with precision snapping, constraint-aware geometry operations, an AutoCAD-style command parser, and multi-format export support for engineering handoff.', NULL, '["Implemented command-driven geometry creation/editing for faster drafting flows.","Added snapping and history systems to support reversible precision operations.","Shipped DXF, SVG, PDF, JSON, and Excel export pathways from a single web workspace.","Maintained responsive interaction in a Fabric.js canvas-based editor architecture."]',
  '["TypeScript","React","Fabric.js","Zustand","Node.js","Express"]', 'https://github.com/Leptons1618/AXCAD', NULL, '2024-06-12', '6 min',
  '## Product Scope

AXCAD focuses on day-to-day drafting workflows in the browser: create/edit geometry, keep precision under control, and export into formats teammates can consume immediately.

## Core Engineering Decisions

1. **Command-first interaction** for geometry operations and power-user speed.
2. **Constraint and snap support** to reduce precision errors during manual editing.
3. **Stateful history management** for safe iteration and rollback.

## Delivery

The tool was designed as a web-native CAD surface with practical export options so users can transition from ideation to downstream tooling without format friction.', '<h2 id="product-scope">Product Scope</h2>
<p>AXCAD focuses on day-to-day drafting workflows in the browser: create/edit geometry, keep precision under control, and export into formats teammates can consume immediately.</p>
<h2 id="core-engineering-decisions">Core Engineering Decisions</h2>
<ol>
<li><strong>Command-first interaction</strong> for geometry operations and power-user speed.</li>
<li><strong>Constraint and snap support</strong> to reduce precision errors during manual editing.</li>
<li><strong>Stateful history management</strong> for safe iteration and rollback.</li>
</ol>
<h2 id="delivery">Delivery</h2>
<p>The tool was designed as a web-native CAD surface with practical export options so users can transition from ideation to downstream tooling without format friction.</p>');
INSERT INTO case_studies (slug, title, subtitle, hero_image, hero_video, problem, solution,
  architecture_image, achievements, stack, repo_url, demo_url, date, read_time, body_md, body_html)
VALUES ('echoscript', 'EchoScript', 'Automatic transcription with speaker diarization using Whisper and PyAnnote.', NULL, NULL,
  'Generating accurate transcripts from multi-speaker audio requires both high-quality ASR and speaker attribution. Whisper alone produces accurate text but does not identify who is speaking.', 'Integrated OpenAI Whisper for ASR with PyAnnote.audio for speaker diarization, aligning speaker labels to transcript segments via timestamp matching.', NULL, '["Per-speaker transcript segments with < 200ms alignment error.","SRT, VTT, and plain text export formats.","Batch processing API for multi-file jobs.","React frontend with waveform visualization using WaveSurfer.js."]',
  '["Python","OpenAI Whisper","PyAnnote","FastAPI","React","TypeScript","WaveSurfer.js"]', 'https://github.com/Leptons1618/EchoScript', NULL, '2024-05-20', '6 min',
  '## Pipeline

1. **Preprocessing**: resample to 16kHz mono, normalize loudness.
2. **Diarization**: PyAnnote.audio segments audio by speaker with RTTM output.
3. **Transcription**: Whisper transcribes each diarized segment independently.
4. **Alignment**: Word-level timestamps from Whisper are matched to diarization segments.

## Export Formats

- **SRT**: speaker-labeled subtitle blocks with timecodes.
- **VTT**: WebVTT format for browser-native subtitle tracks.
- **JSON**: structured data with per-word timing and confidence scores.

## Frontend

WaveSurfer.js renders audio waveforms. Clicking a transcript segment seeks the audio to that position. Speaker colors are assigned per unique speaker ID.', '<h2 id="pipeline">Pipeline</h2>
<ol>
<li><strong>Preprocessing</strong>: resample to 16kHz mono, normalize loudness.</li>
<li><strong>Diarization</strong>: PyAnnote.audio segments audio by speaker with RTTM output.</li>
<li><strong>Transcription</strong>: Whisper transcribes each diarized segment independently.</li>
<li><strong>Alignment</strong>: Word-level timestamps from Whisper are matched to diarization segments.</li>
</ol>
<h2 id="export-formats">Export Formats</h2>
<ul>
<li><strong>SRT</strong>: speaker-labeled subtitle blocks with timecodes.</li>
<li><strong>VTT</strong>: WebVTT format for browser-native subtitle tracks.</li>
<li><strong>JSON</strong>: structured data with per-word timing and confidence scores.</li>
</ul>
<h2 id="frontend">Frontend</h2>
<p>WaveSurfer.js renders audio waveforms. Clicking a transcript segment seeks the audio to that position. Speaker colors are assigned per unique speaker ID.</p>');
INSERT INTO case_studies (slug, title, subtitle, hero_image, hero_video, problem, solution,
  architecture_image, achievements, stack, repo_url, demo_url, date, read_time, body_md, body_html)
VALUES ('ingesta', 'Ingesta', 'High-throughput data ingestion pipeline with reliable batch processing and DLQ.', NULL, NULL,
  'Ingesting high-volume event streams into a relational database is error-prone when individual record failures cause entire batch failures. Retry logic without backoff causes thundering herd problems under load.', 'Built a Kafka consumer pipeline with configurable batch sizes, transactional batch inserts, dead-letter queue routing for failed records, and exponential backoff retry.', NULL, '["Configurable batch insert controls reducing DB round-trips by 85%.","Dead-letter queue with retry and poison-pill detection.","At-least-once delivery with manual Kafka offset commit.","Prometheus metrics for lag, throughput, and error rates."]',
  '["Python","Apache Kafka","PostgreSQL","Redis","Docker","FastAPI"]', 'https://github.com/Leptons1618/Ingesta', NULL, '2024-02-10', '7 min',
  '## Design

Ingesta is a Python service that consumes from Kafka topics and writes to PostgreSQL in batches.

### Batch Strategy

Each consumer thread accumulates records up to a configurable `BATCH_SIZE` or `BATCH_TIMEOUT_MS`, whichever comes first. Batches are inserted in a single multi-row `INSERT`.

### Dead-Letter Queue

Records failing schema validation or DB insertion after `MAX_RETRIES` are routed to a DLQ topic with an error envelope containing the original payload, error type, and timestamp.

### Offset Management

Kafka offsets are committed manually after successful batch insertion, ensuring at-least-once delivery.

## Deployment

Packaged as a Docker container configured via environment variables. A `docker-compose.yml` is provided for local development with Kafka and PostgreSQL.', '<h2 id="design">Design</h2>
<p>Ingesta is a Python service that consumes from Kafka topics and writes to PostgreSQL in batches.</p>
<h3 id="batch-strategy">Batch Strategy</h3>
<p>Each consumer thread accumulates records up to a configurable <code>BATCH_SIZE</code> or <code>BATCH_TIMEOUT_MS</code>, whichever comes first. Batches are inserted in a single multi-row <code>INSERT</code>.</p>
<h3 id="dead-letter-queue">Dead-Letter Queue</h3>
<p>Records failing schema validation or DB insertion after <code>MAX_RETRIES</code> are routed to a DLQ topic with an error envelope containing the original payload, error type, and timestamp.</p>
<h3 id="offset-management">Offset Management</h3>
<p>Kafka offsets are committed manually after successful batch insertion, ensuring at-least-once delivery.</p>
<h2 id="deployment">Deployment</h2>
<p>Packaged as a Docker container configured via environment variables. A <code>docker-compose.yml</code> is provided for local development with Kafka and PostgreSQL.</p>');
INSERT INTO case_studies (slug, title, subtitle, hero_image, hero_video, problem, solution,
  architecture_image, achievements, stack, repo_url, demo_url, date, read_time, body_md, body_html)
VALUES ('markov-chain-lab', 'Markov Chain Lab', 'Interactive learning platform for Markov chains, automata, simulation, and grammar workflows.', NULL, NULL,
  'Students and practitioners need one place to learn theory, build automata, run simulations, and validate behavior; most tools are fragmented across static notes and disconnected utilities.', 'Built a modern Next.js platform with an interactive builder, simulation and analysis tabs, grammar conversion tooling, and persisted user workspaces.', NULL, '["Visual chain builder supports Markov Chains, DFA, and NFA with interactive editing.","Simulation and analysis cover stationary behavior, convergence, and chain properties.","Grammar editor supports two-way grammar↔automata conversion with validation.","User settings and workspace state persist through Supabase integration."]',
  '["Next.js","React","TypeScript","Tailwind CSS","Supabase"]', 'https://github.com/Leptons1618/Markov-Chain-Lab', NULL, '2024-03-01', '5 min',
  '## Overview

Markov Chain Lab is a full learning-and-practice environment that combines lessons, interactive tools, and experimentation workflows in one platform.

## Technical Approach

The core toolset is organized around building state machines, running simulations, and analyzing behavior in real time. Users can switch between Markov Chain, DFA, and NFA modes while preserving a consistent editing workflow.

Conversion utilities bridge formal grammars and automata, while analysis views expose transition behavior and convergence-related properties for iterative experimentation.

## Implementation Notes

The platform is implemented with a Next.js + React + TypeScript frontend and uses Supabase-backed persistence for settings and saved workspace state.', '<h2 id="overview">Overview</h2>
<p>Markov Chain Lab is a full learning-and-practice environment that combines lessons, interactive tools, and experimentation workflows in one platform.</p>
<h2 id="technical-approach">Technical Approach</h2>
<p>The core toolset is organized around building state machines, running simulations, and analyzing behavior in real time. Users can switch between Markov Chain, DFA, and NFA modes while preserving a consistent editing workflow.</p>
<p>Conversion utilities bridge formal grammars and automata, while analysis views expose transition behavior and convergence-related properties for iterative experimentation.</p>
<h2 id="implementation-notes">Implementation Notes</h2>
<p>The platform is implemented with a Next.js + React + TypeScript frontend and uses Supabase-backed persistence for settings and saved workspace state.</p>');
INSERT INTO case_studies (slug, title, subtitle, hero_image, hero_video, problem, solution,
  architecture_image, achievements, stack, repo_url, demo_url, date, read_time, body_md, body_html)
VALUES ('menu-ocr', 'Menu OCR', 'Layout-aware OCR pipeline for extracting structured menu items and prices from noisy restaurant photos.', NULL, NULL,
  'Restaurant menu images are highly inconsistent in layout, font quality, and lighting, which makes raw OCR output unreliable for downstream structured use.', 'Built a modular OCR system combining PaddleOCR and OpenCV preprocessing, then applied DBSCAN-based column grouping, FSM/Viterbi hierarchy enforcement, and Hungarian matching for robust item-price pairing.', NULL, '["Improved extraction quality with layout-aware postprocessing on noisy captures.","Added robust multi-column parsing using DBSCAN clustering.","Enforced semantic structure via FSM + Viterbi decoding for menu hierarchies.","Used global Hungarian assignment to improve item-to-price mapping reliability."]',
  '["Python","PaddleOCR","OpenCV","spaCy","FastAPI","React"]', 'https://github.com/Leptons1618/menu-ocr', NULL, '2023-11-08', '7 min',
  '## Pipeline

1. **Image normalization** for contrast, skew, and noise reduction.
2. **OCR extraction** of text candidates and bounding regions.
3. **Layout reconstruction** to infer columns and item blocks.
4. **Semantic correction** to map sections, items, and prices.

## Why It Worked

The quality improvement came from treating OCR as a full information extraction problem rather than just text recognition, with explicit modeling of layout and business rules.', '<h2 id="pipeline">Pipeline</h2>
<ol>
<li><strong>Image normalization</strong> for contrast, skew, and noise reduction.</li>
<li><strong>OCR extraction</strong> of text candidates and bounding regions.</li>
<li><strong>Layout reconstruction</strong> to infer columns and item blocks.</li>
<li><strong>Semantic correction</strong> to map sections, items, and prices.</li>
</ol>
<h2 id="why-it-worked">Why It Worked</h2>
<p>The quality improvement came from treating OCR as a full information extraction problem rather than just text recognition, with explicit modeling of layout and business rules.</p>');
INSERT INTO case_studies (slug, title, subtitle, hero_image, hero_video, problem, solution,
  architecture_image, achievements, stack, repo_url, demo_url, date, read_time, body_md, body_html)
VALUES ('querypilot', 'QueryPilot', 'Schema-aware natural-language-to-SQL workflow with validation and explainability.', NULL, NULL,
  'Text-to-SQL assistants often produce unsafe or invalid queries when they lack schema context and execution safeguards.', 'Built a schema-aware generation pipeline that reads live metadata, produces SQL from user intent, validates before execution, and returns both query output and human-readable SQL explanations.', NULL, '["Reduced invalid query execution with pre-run validation checks.","Improved generation quality via schema-aware prompt construction.","Added SQL explanation output for trust and review workflows.","Exposed end-to-end workflow through FastAPI + React interface."]',
  '["Python","FastAPI","SQLAlchemy","PostgreSQL","React","TypeScript"]', 'https://github.com/Leptons1618/QueryPilot', NULL, '2024-08-05', '6 min',
  '## Workflow

1. Inspect live database schema and relationships.
2. Build constrained prompt context for query generation.
3. Validate generated SQL before any execution step.
4. Return results plus explanation for user verification.

## Key Outcome

By combining schema grounding and a validation gate, QueryPilot balances usability with safer execution behavior.', '<h2 id="workflow">Workflow</h2>
<ol>
<li>Inspect live database schema and relationships.</li>
<li>Build constrained prompt context for query generation.</li>
<li>Validate generated SQL before any execution step.</li>
<li>Return results plus explanation for user verification.</li>
</ol>
<h2 id="key-outcome">Key Outcome</h2>
<p>By combining schema grounding and a validation gate, QueryPilot balances usability with safer execution behavior.</p>');
INSERT INTO case_studies (slug, title, subtitle, hero_image, hero_video, problem, solution,
  architecture_image, achievements, stack, repo_url, demo_url, date, read_time, body_md, body_html)
VALUES ('streamfusion', 'StreamFusion', 'Realtime watch-party experience with synchronized playback, shared queue, and in-room chat.', NULL, NULL,
  'Watch-party apps fail quickly when playback drift accumulates across devices, leading to broken group experiences and fragmented session state.', 'Built a room-based sync architecture using WebRTC data channels and WebSocket signaling, with reconciliation logic for playback state, queue coordination, and chat delivery.', NULL, '["Maintained low drift across participants with periodic sync reconciliation.","Implemented shared queue controls with multi-user conflict handling.","Delivered integrated chat tied to room session state.","Shipped cross-platform mobile client with Expo + React Native."]',
  '["React Native","Expo","TypeScript","WebRTC","Zustand","WebSocket","Node.js"]', 'https://github.com/Leptons1618/streamfusion', NULL, '2023-09-16', '5 min',
  '## System Design

StreamFusion separates signaling from realtime room state to keep sessions recoverable and resilient during reconnects.

## Realtime Strategy

- WebRTC channels carry latency-sensitive sync events.
- WebSocket signaling coordinates room membership and negotiation.
- Client-side state management keeps playback and queue views consistent.', '<h2 id="system-design">System Design</h2>
<p>StreamFusion separates signaling from realtime room state to keep sessions recoverable and resilient during reconnects.</p>
<h2 id="realtime-strategy">Realtime Strategy</h2>
<ul>
<li>WebRTC channels carry latency-sensitive sync events.</li>
<li>WebSocket signaling coordinates room membership and negotiation.</li>
<li>Client-side state management keeps playback and queue views consistent.</li>
</ul>');
INSERT INTO case_studies (slug, title, subtitle, hero_image, hero_video, problem, solution,
  architecture_image, achievements, stack, repo_url, demo_url, date, read_time, body_md, body_html)
VALUES ('streamsql', 'StreamSQL', 'Real-time SQL Server CDC streaming through Debezium/Kafka into MQTT subscribers.', NULL, NULL,
  'Operational analytics pipelines often need low-latency change propagation from transactional databases to event-driven consumers, but direct polling introduces delay and consistency issues.', 'Implemented a CDC-first architecture using Debezium + Kafka Connect for SQL Server change capture, with Kafka topics bridged to MQTT for low-latency downstream consumption and monitoring.', NULL, '["Delivered near-real-time CDC propagation from SQL Server to event consumers.","Added Kafka-to-MQTT bridge for subscriber-friendly fan-out.","Packaged local reproducible stack with Docker and Kafka UI/Connect tooling.","Improved observability of connector and topic health during iteration."]',
  '["Python","Apache Kafka","Debezium","Kafka Connect","MQTT","Docker","SQL Server"]', 'https://github.com/Leptons1618/StreamSQL', NULL, '2024-07-01', '6 min',
  '## Architecture

The data path is:

`SQL Server (CDC) -> Debezium Connector -> Kafka Topics -> MQTT Bridge -> Subscribers`

## Reliability Notes

- Connector-driven CDC removed application-level polling complexity.
- Topic-based buffering enabled decoupled consumers.
- Dockerized dependencies reduced setup variance across environments.', '<h2 id="architecture">Architecture</h2>
<p>The data path is:</p>
<p><code>SQL Server (CDC) -> Debezium Connector -> Kafka Topics -> MQTT Bridge -> Subscribers</code></p>
<h2 id="reliability-notes">Reliability Notes</h2>
<ul>
<li>Connector-driven CDC removed application-level polling complexity.</li>
<li>Topic-based buffering enabled decoupled consumers.</li>
<li>Dockerized dependencies reduced setup variance across environments.</li>
</ul>');
INSERT INTO case_studies (slug, title, subtitle, hero_image, hero_video, problem, solution,
  architecture_image, achievements, stack, repo_url, demo_url, date, read_time, body_md, body_html)
VALUES ('visionid', 'VisionID', 'Real-time multi-object detection and tracking with YOLOv8 and DeepSort.', NULL, NULL,
  'Tracking multiple objects across video frames requires balancing detection accuracy with tracking continuity. YOLO alone loses object identity across frames, while naive IoU tracking fails under occlusion.', 'Combined YOLOv8 for per-frame detection with DeepSort for appearance-based re-identification, exposed through a FastAPI interface supporting both batch video and live stream inputs.', NULL, '["25 FPS real-time tracking on a single consumer GPU.","Per-object track ID stability across occlusions via appearance embedding.","REST API with configurable detection thresholds.","JSON output with bounding boxes, class labels, and track IDs per frame."]',
  '["Python","PyTorch","YOLOv8","DeepSort","OpenCV","FastAPI"]', 'https://github.com/Leptons1618/VisionID', NULL, '2024-04-15', '6 min',
  '## Architecture

The pipeline runs in two stages:

1. **Detection**: YOLOv8n processes each frame and returns bounding boxes with class scores.
2. **Tracking**: DeepSort assigns consistent IDs by matching detections against existing tracks using Kalman filter prediction and cosine similarity on appearance embeddings.

## API Design

Two endpoints:
- `POST /track/video` — processes uploaded video and returns tracking JSON.
- `GET /track/stream` — SSE endpoint for live tracking data.

## Tuning Notes

Confidence threshold 0.45 and NMS IoU 0.5 gave the best balance on the traffic camera test set. Track confirmation requires 3 consecutive detections.', '<h2 id="architecture">Architecture</h2>
<p>The pipeline runs in two stages:</p>
<ol>
<li><strong>Detection</strong>: YOLOv8n processes each frame and returns bounding boxes with class scores.</li>
<li><strong>Tracking</strong>: DeepSort assigns consistent IDs by matching detections against existing tracks using Kalman filter prediction and cosine similarity on appearance embeddings.</li>
</ol>
<h2 id="api-design">API Design</h2>
<p>Two endpoints:</p>
<ul>
<li><code>POST /track/video</code> — processes uploaded video and returns tracking JSON.</li>
<li><code>GET /track/stream</code> — SSE endpoint for live tracking data.</li>
</ul>
<h2 id="tuning-notes">Tuning Notes</h2>
<p>Confidence threshold 0.45 and NMS IoU 0.5 gave the best balance on the traffic camera test set. Track confirmation requires 3 consecutive detections.</p>');

-- Projects. Frontmatter only — no page renders a project body.
INSERT INTO projects (slug, title, summary, category, tags, stack, repo_url, demo_url,
  case_study_slug, featured_rank, status, year, hero_image, highlights, hidden)
VALUES ('axcad', 'AXCAD', 'Web-based 2D CAD editor with parametric constraints and DXF export support.', 'devtools', '["cad","parametric","constraints","dxf","typescript"]',
  '["TypeScript","React","Fabric.js","Zustand","Node.js","Express"]', 'https://github.com/Leptons1618/AXCAD', NULL, 'axcad',
  1, 'wip', 2024, NULL,
  '["Built a full CAD workspace with snapping, history management, and precision drafting tools.","Implemented an AutoCAD-style command parser for geometry creation/editing workflows.","Added multi-format export pathways (DXF, SVG, PDF, JSON, and Excel) from the web editor."]', 1);
INSERT INTO projects (slug, title, summary, category, tags, stack, repo_url, demo_url,
  case_study_slug, featured_rank, status, year, hero_image, highlights, hidden)
VALUES ('comic-sudoku', 'Comic Sudoku', 'Sudoku game with a comic art style theme and a built-in constraint-satisfaction solver.', 'other', '["game","sudoku","solver","csp","javascript"]',
  '["JavaScript","HTML Canvas","CSS","Backtracking","CSP"]', 'https://github.com/Leptons1618/Comic-Sudoku', NULL, NULL,
  NULL, 'stable', 2023, NULL,
  '["Implemented backtracking CSP solver with arc-consistency pruning.","Hand-drawn comic art style UI rendered on HTML Canvas.","Puzzle generator with difficulty classification via filled-cell count."]', 0);
INSERT INTO projects (slug, title, summary, category, tags, stack, repo_url, demo_url,
  case_study_slug, featured_rank, status, year, hero_image, highlights, hidden)
VALUES ('dwg2svg', 'dwg2svg', 'CAD conversion toolkit for SVG↔DXF workflows with block attributes and coordinate mapping.', 'other', '["cad","dwg","dxf","svg","conversion"]',
  '["React","Node.js","Express","Python","Flask","ezdxf","lxml"]', 'https://github.com/Leptons1618/dwg2svg', NULL, NULL,
  NULL, 'stable', 2023, NULL,
  '["Implements a 3-service architecture (React UI, Node backend, Python conversion engine).","Handles SVG-to-DXF block generation with ATTDEF/ATTRIB support and base-point selection.","Includes DXF↔SVG conversion improvements for geometry fidelity and hatch rendering."]', 0);
INSERT INTO projects (slug, title, summary, category, tags, stack, repo_url, demo_url,
  case_study_slug, featured_rank, status, year, hero_image, highlights, hidden)
VALUES ('echonode', 'EchoNode', 'Distributed event-driven node framework for building fault-tolerant microservices.', 'systems', '["distributed-systems","event-driven","microservices","nodejs","fault-tolerance"]',
  '["Node.js","TypeScript","RabbitMQ","Redis","Docker","Prometheus"]', 'https://github.com/Leptons1618/EchoNode', NULL, NULL,
  NULL, 'stable', 2023, NULL,
  '["Implements saga pattern for distributed transaction coordination.","Automatic service health checks and circuit breaker via Redis TTL.","Event replay from RabbitMQ dead-letter exchange for debugging."]', 0);
INSERT INTO projects (slug, title, summary, category, tags, stack, repo_url, demo_url,
  case_study_slug, featured_rank, status, year, hero_image, highlights, hidden)
VALUES ('echoscript', 'EchoScript', 'YouTube transcription and AI note-taking app with synchronized playback and search.', 'ai-llm', '["speech-recognition","youtube","transcription","whisper","summarization"]',
  '["Python","Flask","React","OpenAI Whisper","Faster-Whisper","yt-dlp","ffmpeg"]', 'https://github.com/Leptons1618/EchoScript', NULL, 'echoscript',
  4, 'active', 2024, NULL,
  '["Transcribes YouTube content using Whisper/Faster-Whisper with configurable model settings.","Synchronizes transcript segments with video playback for interactive review.","Generates AI notes/summaries and supports export to PDF, TXT, and Notion.","Provides searchable job history with transcript filtering and keyboard-driven navigation."]', 0);
INSERT INTO projects (slug, title, summary, category, tags, stack, repo_url, demo_url,
  case_study_slug, featured_rank, status, year, hero_image, highlights, hidden)
VALUES ('ingesta', 'Ingesta', 'High-throughput data ingestion pipeline with configurable batch processing and dead-letter queuing.', 'full-stack', '["data-pipeline","ingestion","batch-processing","kafka","python"]',
  '["Python","Apache Kafka","PostgreSQL","Redis","Docker","FastAPI"]', 'https://github.com/Leptons1618/Ingesta', NULL, 'ingesta',
  NULL, 'stable', 2024, NULL,
  '["Implemented configurable batch insert controls to improve reliability for high-volume ingestion.","Added dead-letter queue with automatic retry and exponential backoff.","Kafka consumer groups with manual offset commit for at-least-once delivery.","Monitoring dashboard via Prometheus metrics and Grafana."]', 0);
INSERT INTO projects (slug, title, summary, category, tags, stack, repo_url, demo_url,
  case_study_slug, featured_rank, status, year, hero_image, highlights, hidden)
VALUES ('localrag', 'LocalRAG', 'Local retrieval-augmented generation system using open-source LLMs and vector search.', 'ai-llm', '["rag","llm","vector-search","embeddings","local-ai"]',
  '["Python","LlamaIndex","ChromaDB","Ollama","FastAPI","React"]', 'https://github.com/Leptons1618/LocalRAG', NULL, NULL,
  NULL, 'active', 2024, NULL,
  '["Fully local pipeline: no external API calls, runs on consumer hardware.","Document ingestion with chunking, embedding, and ChromaDB storage.","Supports multiple local LLM backends via Ollama (Mistral, Llama3, Phi3).","Context window management with source citation in responses."]', 0);
INSERT INTO projects (slug, title, summary, category, tags, stack, repo_url, demo_url,
  case_study_slug, featured_rank, status, year, hero_image, highlights, hidden)
VALUES ('markov-chain-lab', 'Markov Chain Lab', 'Interactive learning platform for Markov chains, automata, and grammar conversion.', 'simulation', '["markov-chains","automata","simulation","education","interactive"]',
  '["Next.js","React","TypeScript","Tailwind CSS","Supabase"]', 'https://github.com/Leptons1618/Markov-Chain-Lab', NULL, 'markov-chain-lab',
  2, 'stable', 2024, NULL,
  '["Built an interactive chain builder supporting Markov chains, DFA, and NFA workflows.","Added simulation and analysis modules for convergence, stationary distribution, and chain properties.","Implemented grammar-to-automata and automata-to-grammar conversion utilities.","Integrated Supabase-backed persistence for saved workspaces and user settings."]', 0);
INSERT INTO projects (slug, title, summary, category, tags, stack, repo_url, demo_url,
  case_study_slug, featured_rank, status, year, hero_image, highlights, hidden)
VALUES ('menu-ocr', 'Menu OCR', 'OCR pipeline for extracting structured restaurant menu content from images.', 'ml-cv', '["ocr","computer-vision","text-extraction","image-processing","nlp"]',
  '["Python","PaddleOCR","OpenCV","spaCy","FastAPI","React"]', 'https://github.com/Leptons1618/menu-ocr', NULL, 'menu-ocr',
  3, 'stable', 2023, NULL,
  '["Implemented a modular OCR pipeline with layout-aware postprocessing and diagnostics.","Added column detection with DBSCAN plus hierarchy enforcement using FSM + Viterbi decoding.","Used Hungarian matching for robust global item-price association across noisy menus."]', 0);
INSERT INTO projects (slug, title, summary, category, tags, stack, repo_url, demo_url,
  case_study_slug, featured_rank, status, year, hero_image, highlights, hidden)
VALUES ('metastream-mobile', 'MetaStream Mobile', 'Cross-platform mobile watch-party app with realtime room sync, queue, and chat.', 'other', '["mobile","watch-party","react-native","sync","chat"]',
  '["React Native","Expo","TypeScript","Expo Router","Zustand","WebSocket","Node.js"]', 'https://github.com/Leptons1618/metastream-mobile', NULL, NULL,
  NULL, 'stable', 2023, NULL,
  '["Implements room-based synchronized playback with host-controlled realtime updates.","Supports shared media queue and in-room chat over a self-hostable signal server.","Includes Android APK CI workflow and tag-based release publishing."]', 0);
INSERT INTO projects (slug, title, summary, category, tags, stack, repo_url, demo_url,
  case_study_slug, featured_rank, status, year, hero_image, highlights, hidden)
VALUES ('mlevaluation', 'MLEvaluation', 'Evaluation harness for ML experiments with standardized metrics and reports.', 'devtools', '["ml","evaluation","metrics","benchmarking","mlops"]',
  '["Python","scikit-learn","PyTorch","MLflow","Pandas","Plotly"]', 'https://github.com/Leptons1618/MLEvaluation', NULL, NULL,
  NULL, 'stable', 2024, NULL,
  '["Unified classification and regression metrics under one runner.","Integrated MLflow tracking for run comparison and reproducibility.","Generated HTML reports with metric trends and confusion matrices."]', 0);
INSERT INTO projects (slug, title, summary, category, tags, stack, repo_url, demo_url,
  case_study_slug, featured_rank, status, year, hero_image, highlights, hidden)
VALUES ('nicechatai', 'NiceChatAI', 'Conversational AI frontend with multi-model support and conversation management.', 'ai-llm', '["chatbot","llm","openai","conversation","react"]',
  '["React","TypeScript","OpenAI API","Zustand","Tailwind","FastAPI"]', 'https://github.com/Leptons1618/NiceChatAI', NULL, NULL,
  NULL, 'active', 2024, NULL,
  '["Supports GPT-4, Claude, and Gemini through a unified model adapter layer.","Conversation branching and history persistence via IndexedDB.","Streaming response rendering with token-by-token display.","System prompt editor with template library."]', 0);
INSERT INTO projects (slug, title, summary, category, tags, stack, repo_url, demo_url,
  case_study_slug, featured_rank, status, year, hero_image, highlights, hidden)
VALUES ('querypilot', 'QueryPilot', 'Natural-language-to-SQL assistant with schema-aware query generation.', 'ai-llm', '["nlp","sql","llm","text-to-sql","databases"]',
  '["Python","FastAPI","SQLAlchemy","PostgreSQL","React","TypeScript"]', 'https://github.com/Leptons1618/QueryPilot', NULL, 'querypilot',
  NULL, 'active', 2024, NULL,
  '["Built schema-aware prompt construction from live database metadata.","Added SQL validation stage before execution to reduce invalid queries.","Exposed both query output and SQL explanation for review workflows."]', 0);
INSERT INTO projects (slug, title, summary, category, tags, stack, repo_url, demo_url,
  case_study_slug, featured_rank, status, year, hero_image, highlights, hidden)
VALUES ('sia-proto', 'SIA Proto', 'Local-first system monitoring agent with event analysis, CLI, and optional Ollama integration.', 'other', '["system-monitoring","rust","cli","sqlite","agent"]',
  '["Rust","Tokio","SQLite","sqlx","clap","systemd","Ollama"]', 'https://github.com/Leptons1618/sia-proto', NULL, NULL,
  NULL, 'wip', 2024, NULL,
  '["Runs as a background Linux agent with CPU/memory monitoring and event generation.","Exposes a Unix-socket JSON-RPC interface with a dedicated CLI for status and event inspection.","Stores telemetry/events in SQLite and optionally enriches insights via local Ollama models."]', 0);
INSERT INTO projects (slug, title, summary, category, tags, stack, repo_url, demo_url,
  case_study_slug, featured_rank, status, year, hero_image, highlights, hidden)
VALUES ('ssh-key-gui', 'SSH Key GUI', 'Desktop GUI for generating, managing, and deploying SSH key pairs.', 'devtools', '["ssh","keygen","desktop-app","security","gui"]',
  '["Python","Tkinter","Paramiko","Cryptography","subprocess"]', 'https://github.com/Leptons1618/ssh-key-gui', NULL, NULL,
  NULL, 'stable', 2023, NULL,
  '["Generates RSA, Ed25519, and ECDSA key pairs via Python cryptography library.","One-click deployment of public keys to remote hosts via Paramiko.","Stores key metadata locally with optional passphrase encryption."]', 0);
INSERT INTO projects (slug, title, summary, category, tags, stack, repo_url, demo_url,
  case_study_slug, featured_rank, status, year, hero_image, highlights, hidden)
VALUES ('streamfusion', 'StreamFusion', 'Cross-platform synchronized watch-party app with realtime playback, queue, and chat.', 'other', '["watch-party","realtime","webrtc","mobile","streaming"]',
  '["React Native","Expo","TypeScript","WebRTC","Zustand","WebSocket","Node.js"]', 'https://github.com/Leptons1618/streamfusion', NULL, 'streamfusion',
  NULL, 'stable', 2023, NULL,
  '["Implements room-based realtime playback sync with low drift using WebRTC data channels.","Includes chat and shared queue management for multi-user sessions.","Ships with a Node.js signal server and Expo-based mobile client architecture."]', 0);
INSERT INTO projects (slug, title, summary, category, tags, stack, repo_url, demo_url,
  case_study_slug, featured_rank, status, year, hero_image, highlights, hidden)
VALUES ('streamsql', 'StreamSQL', 'Real-time CDC pipeline from SQL Server through Debezium/Kafka to MQTT consumers.', 'systems', '["sql","streaming","kafka","real-time","analytics"]',
  '["Python","Apache Kafka","Debezium","Kafka Connect","MQTT","Docker","SQL Server"]', 'https://github.com/Leptons1618/StreamSQL', NULL, 'streamsql',
  5, 'active', 2024, NULL,
  '["Streams SQL Server CDC changes through Debezium into Kafka topics in near real time.","Bridges Kafka change events to HiveMQ MQTT topics for low-latency subscribers.","Ships with Docker-based local stack and operational monitoring via Kafka UI/Connect."]', 0);
INSERT INTO projects (slug, title, summary, category, tags, stack, repo_url, demo_url,
  case_study_slug, featured_rank, status, year, hero_image, highlights, hidden)
VALUES ('trustnet', 'TrustNet', 'Explainable and trust-aware image classification prototype with uncertainty and OOD analysis.', 'other', '["trust-ai","xai","uncertainty","ood-detection","computer-vision"]',
  '["Python","PyTorch","Streamlit","Grad-CAM","ODIN","Mahalanobis","CIFAR-10"]', 'https://github.com/Leptons1618/TrustNet', NULL, NULL,
  NULL, 'stable', 2023, NULL,
  '["Implements uncertainty quantification and calibration for model confidence reliability.","Adds OOD detection via ODIN and Mahalanobis methods for trust-aware decisions.","Provides Grad-CAM visual explanations through an interactive Streamlit interface."]', 0);
INSERT INTO projects (slug, title, summary, category, tags, stack, repo_url, demo_url,
  case_study_slug, featured_rank, status, year, hero_image, highlights, hidden)
VALUES ('vehicle-speed-estimation', 'Vehicle Speed Estimation', 'Computer vision pipeline for estimating vehicle speed from traffic video.', 'ml-cv', '["computer-vision","tracking","speed","yolo","traffic"]',
  '["Python","YOLOv8","DeepSort","OpenCV","NumPy","FastAPI"]', 'https://github.com/Leptons1618/vehicle_speed_estimation', NULL, NULL,
  NULL, 'stable', 2023, NULL,
  '["Estimated vehicle velocity using projected movement across calibrated scenes.","Maintained object identity with multi-object tracking across occlusions.","Added smoothing and confidence thresholds for stable speed outputs."]', 0);
INSERT INTO projects (slug, title, summary, category, tags, stack, repo_url, demo_url,
  case_study_slug, featured_rank, status, year, hero_image, highlights, hidden)
VALUES ('visionid', 'VisionID', 'Computer vision system for real-time object identification and tracking using YOLO and DeepSort.', 'ml-cv', '["object-detection","tracking","computer-vision","yolo","real-time"]',
  '["Python","PyTorch","YOLOv8","DeepSort","OpenCV","FastAPI"]', 'https://github.com/Leptons1618/VisionID', NULL, 'visionid',
  NULL, 'active', 2024, NULL,
  '["Integrated YOLOv8 for detection with DeepSort multi-object tracker.","Achieved real-time inference at 25 FPS on a single GPU.","Built REST API with FastAPI for programmatic access to detection pipeline.","Added configurable confidence and NMS thresholds for precision/recall tuning."]', 0);
INSERT INTO projects (slug, title, summary, category, tags, stack, repo_url, demo_url,
  case_study_slug, featured_rank, status, year, hero_image, highlights, hidden)
VALUES ('visionplay', 'VisionPlay', 'Browser-based computer vision playground using TensorFlow.js for in-browser inference.', 'ml-cv', '["tensorflow.js","computer-vision","browser-ml","webcam","real-time"]',
  '["TypeScript","TensorFlow.js","React","WebGL","Vite"]', 'https://github.com/Leptons1618/VisionPlay', NULL, NULL,
  NULL, 'stable', 2023, NULL,
  '["Implemented TFJS digit classifier packaging (model.json + weights) for in-app inference.","WebGL-accelerated inference pipeline with canvas-based video frame extraction.","Supports model hot-swap at runtime without page reload.","Mobile-compatible with MediaDevices API for camera access."]', 0);

-- Journal. `status` is required here for the same reason
-- check-content.mjs required it: the schema default is for the editor.
INSERT INTO journal (slug, title, summary, date, tags, read_time, video_duration,
  hero_image, status, body_md, body_html)
VALUES ('rebuilding-the-portfolio-on-a-design-system', 'Rebuilding the portfolio on a real design system', 'Swapping two hand-tuned themes for one Modernist token set — what a design system actually removes, and why the CSS got shorter.', '2026-08-14', '["Design Systems","Astro","CSS"]',
  '5 min', NULL, NULL, 'published',
  'This site used to ship two complete visual identities. One was `pixel`: a PICO-8 palette on near-black, Press Start 2P headings, a CRT scanline overlay painted over the whole viewport, and hard offset shadows that snapped on hover. The other was `paper`: cream stock, a typewriter face, cards with ragged SVG tear edges and a half-degree rotation so the page read like scraps on a desk. A toggle in the header cycled between them and a system preference.

Both were fun. Neither was a system.

## What actually got deleted

The rebuild moved everything onto Modernist — a flat, architectural set of tokens: one warm off-white ground, one ink, one red accent, Archivo throughout, zero corner radius, 2px rules doing all the organising.

The interesting part is what that made redundant:

- Two full token blocks in `theme.css`, plus every `html[data-theme=...]` override in `global.css`.
- The inline head script that resolved the stored theme before first paint, and the `ThemeToggle` component behind it.
- Four webfont packages. Press Start 2P, VT323, Special Elite and IBM Plex Serif all left with the themes that needed them.
- Every decorative layer: the fixed background grids, the scanline `::after`, the radial glows, the gradient-text helper, the boot and settle keyframes.

`global.css` came out roughly 40% shorter, and almost none of that was code I had to think hard about removing. It was all there to serve a choice the design system had already made.

## The rule that did the most work

Modernist''s guidance is blunt about one thing:

> Never hard-code a hex, a font name or a px value the tokens already carry.

Following it literally is what turns a palette into a system. Once every spacing value is `var(--space-*)` and every surface is `var(--color-surface)`, a page stops having its own opinions. Adding the journal section afterwards took no new CSS at all beyond layout — the cards, tags, rules and prose treatment were already defined.

## The one place the accent runs free

The system is mostly ink on ground; red is reserved for the primary action and small emphasis. The documented exception is the closing banner, where the accent runs as a full field and display-grade type carries the page. That''s the only saturated surface on the site, and it earns its place precisely because nothing else competes with it.

## What I''d keep from the old themes

Honestly: the constraint. Both retired themes were rigid in their own way — `pixel` refused to round a corner, `paper` refused to sit straight — and that rigidity is what made them coherent. Modernist has the same quality, just written down where a second person could follow it.', '<p>This site used to ship two complete visual identities. One was <code>pixel</code>: a PICO-8 palette on near-black, Press Start 2P headings, a CRT scanline overlay painted over the whole viewport, and hard offset shadows that snapped on hover. The other was <code>paper</code>: cream stock, a typewriter face, cards with ragged SVG tear edges and a half-degree rotation so the page read like scraps on a desk. A toggle in the header cycled between them and a system preference.</p>
<p>Both were fun. Neither was a system.</p>
<h2 id="what-actually-got-deleted">What actually got deleted</h2>
<p>The rebuild moved everything onto Modernist — a flat, architectural set of tokens: one warm off-white ground, one ink, one red accent, Archivo throughout, zero corner radius, 2px rules doing all the organising.</p>
<p>The interesting part is what that made redundant:</p>
<ul>
<li>Two full token blocks in <code>theme.css</code>, plus every <code>html[data-theme=...]</code> override in <code>global.css</code>.</li>
<li>The inline head script that resolved the stored theme before first paint, and the <code>ThemeToggle</code> component behind it.</li>
<li>Four webfont packages. Press Start 2P, VT323, Special Elite and IBM Plex Serif all left with the themes that needed them.</li>
<li>Every decorative layer: the fixed background grids, the scanline <code>::after</code>, the radial glows, the gradient-text helper, the boot and settle keyframes.</li>
</ul>
<p><code>global.css</code> came out roughly 40% shorter, and almost none of that was code I had to think hard about removing. It was all there to serve a choice the design system had already made.</p>
<h2 id="the-rule-that-did-the-most-work">The rule that did the most work</h2>
<p>Modernist’s guidance is blunt about one thing:</p>
<blockquote>
<p>Never hard-code a hex, a font name or a px value the tokens already carry.</p>
</blockquote>
<p>Following it literally is what turns a palette into a system. Once every spacing value is <code>var(--space-*)</code> and every surface is <code>var(--color-surface)</code>, a page stops having its own opinions. Adding the journal section afterwards took no new CSS at all beyond layout — the cards, tags, rules and prose treatment were already defined.</p>
<h2 id="the-one-place-the-accent-runs-free">The one place the accent runs free</h2>
<p>The system is mostly ink on ground; red is reserved for the primary action and small emphasis. The documented exception is the closing banner, where the accent runs as a full field and display-grade type carries the page. That’s the only saturated surface on the site, and it earns its place precisely because nothing else competes with it.</p>
<h2 id="what-id-keep-from-the-old-themes">What I’d keep from the old themes</h2>
<p>Honestly: the constraint. Both retired themes were rigid in their own way — <code>pixel</code> refused to round a corner, <code>paper</code> refused to sit straight — and that rigidity is what made them coherent. Modernist has the same quality, just written down where a second person could follow it.</p>');
