/**
 * Turn `src/content/` into the SQL that seeds D1, once.
 *
 * This is the one-way door in the migration: after it runs, D1 is the source
 * of truth and these files are history. It is written as a migration rather
 * than a throwaway because a fresh database — a `--local` one for development,
 * or a rebuilt remote — should come up holding the same content, and that is
 * exactly what `migrations/` is for.
 *
 * Bodies are rendered here rather than at request time, and rendered with
 * Astro's own processor rather than a smaller one, so the HTML D1 serves is
 * the HTML this site already served: same GFM, same smartypants, same
 * autolinking. `@astrojs/markdown-remark` is already installed as a dependency
 * of `astro` — this adds nothing to the tree.
 */

import { readdir, readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';
import { parse as parseYaml } from 'yaml';
import { createMarkdownProcessor } from '@astrojs/markdown-remark';

const CONTENT = fileURLToPath(new URL('../src/content/', import.meta.url));
const OUT = fileURLToPath(new URL('../migrations/0002_seed_from_content.sql', import.meta.url));

/**
 * Split a content file into its frontmatter and its body.
 *
 * Astro's own loader is not reachable from a plain Node script, so this repeats
 * the one rule that matters: a leading `---` line opens the block and the next
 * `---` on its own line closes it. Anything else is a file Astro would have
 * rejected at build time, and it throws here rather than seeding a row whose
 * frontmatter silently became part of the body.
 */
function split(raw, file) {
  const text = raw.replace(/^﻿/, '').replace(/\r\n/g, '\n');
  const match = /^---\n([\s\S]*?)\n---\n?/.exec(text);
  if (!match) throw new Error(`${file}: no frontmatter block`);
  return { data: parseYaml(match[1]) ?? {}, body: text.slice(match[0].length).trim() };
}

/** SQLite literal. `null` stays NULL; everything else is a quoted string. */
const q = v => (v === undefined || v === null ? 'NULL' : `'${String(v).replace(/'/g, "''")}'`);
/** Arrays are stored as JSON text — SQLite has no array type. */
const json = v => q(JSON.stringify(v ?? []));
/** SQLite has no boolean either. */
const bool = v => (v ? 1 : 0);
const num = v => (v === undefined || v === null ? 'NULL' : Number(v));

async function collection(dir) {
  const base = join(CONTENT, dir);
  const files = (await readdir(base)).filter(f => f.endsWith('.md') || f.endsWith('.mdx')).sort();
  return Promise.all(
    files.map(async file => {
      const raw = await readFile(join(base, file), 'utf8');
      // Astro derives the slug from the filename, and so does this. Keeping
      // that rule in one place is why the schema has no `slug` column to set
      // independently — see the note in CLAUDE.md about not adding one.
      return { slug: file.replace(/\.mdx?$/, ''), ...split(raw, file) };
    }),
  );
}

const md = await createMarkdownProcessor({});
const html = async body => (body ? (await md.render(body)).code : '');

const caseStudies = await collection('case-studies');
const projects = await collection('projects');
const journal = await collection('journal');

const lines = [
  '-- Generated by `npm run seed:d1` from src/content/. Do not hand-edit:',
  '-- regenerate it, or change the row in D1, which is the source of truth',
  '-- once this has been applied.',
  '',
  'PRAGMA foreign_keys = ON;',
  '',
  '-- Case studies first: `projects.case_study_slug` is a foreign key into this',
  '-- table, so a project inserted before its case study would be refused.',
];

for (const { slug, data: d, body } of caseStudies) {
  lines.push(
    `INSERT INTO case_studies (slug, title, subtitle, hero_image, hero_video, problem, solution,
  architecture_image, achievements, stack, repo_url, demo_url, date, read_time, body_md, body_html)
VALUES (${q(slug)}, ${q(d.title)}, ${q(d.subtitle)}, ${q(d.heroImage)}, ${q(d.heroVideo)},
  ${q(d.problem)}, ${q(d.solution)}, ${q(d.architectureImage)}, ${json(d.achievements)},
  ${json(d.stack)}, ${q(d.repoUrl)}, ${q(d.demoUrl)}, ${q(d.date)}, ${q(d.readTime)},
  ${q(body)}, ${q(await html(body))});`,
  );
}

lines.push('', '-- Projects. Frontmatter only — no page renders a project body.');
for (const { slug, data: d } of projects) {
  lines.push(
    `INSERT INTO projects (slug, title, summary, category, tags, stack, repo_url, demo_url,
  case_study_slug, featured_rank, status, year, hero_image, highlights, hidden)
VALUES (${q(slug)}, ${q(d.title)}, ${q(d.summary)}, ${q(d.category)}, ${json(d.tags)},
  ${json(d.stack)}, ${q(d.repoUrl)}, ${q(d.demoUrl)}, ${q(d.caseStudySlug)},
  ${num(d.featuredRank)}, ${q(d.status)}, ${num(d.year)}, ${q(d.heroImage)},
  ${json(d.highlights)}, ${bool(d.hidden)});`,
  );
}

lines.push('', '-- Journal. `status` is required here for the same reason', '-- check-content.mjs required it: the schema default is for the editor.');
for (const { slug, data: d, body } of journal) {
  if (!d.status) throw new Error(`journal/${slug}: missing status`);
  lines.push(
    `INSERT INTO journal (slug, title, summary, date, tags, read_time, video_duration,
  hero_image, status, body_md, body_html)
VALUES (${q(slug)}, ${q(d.title)}, ${q(d.summary)}, ${q(d.date)}, ${json(d.tags)},
  ${q(d.readTime)}, ${q(d.videoDuration)}, ${q(d.heroImage)}, ${q(d.status)},
  ${q(body)}, ${q(await html(body))});`,
  );
}

await writeFile(OUT, lines.join('\n') + '\n', 'utf8');
console.log(
  `seed written: ${caseStudies.length} case studies, ${projects.length} projects, ${journal.length} posts`,
);
