#!/usr/bin/env node
/**
 * Writes `wrangler.jsonc` from `wrangler.example.jsonc`, substituting the D1
 * database id.
 *
 * ## Why this exists
 *
 * `database_id` names a specific database inside a specific Cloudflare
 * account. Committed, it makes the repository unusable by anyone else: a fork
 * gets a config pointing at the original author's database, and the first
 * `wrangler dev` either fails or — worse, with the right credentials in the
 * environment — succeeds against the wrong data.
 *
 * Wrangler has no environment-variable interpolation in its config and no
 * local override file that gets merged, so there is no built-in way to leave
 * the value out. This is the smallest thing that does: one substitution, from
 * `.env` locally and from the environment in CI.
 *
 * ponytail: one placeholder, replaced literally. If a second value ever needs
 * this treatment, add it to the same map rather than reaching for a templating
 * dependency — but think first about whether it belongs in the config at all.
 *
 * Run by `npm run config`, and by `npm run prepare` after every install.
 * Self-check: `node scripts/wrangler-config.mjs --self-test`.
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, resolve } from 'node:path';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const p = (...parts) => join(root, ...parts);

export const PLACEHOLDER = '__D1_DATABASE_ID__';
const TEMPLATE = 'wrangler.example.jsonc';
const OUTPUT = 'wrangler.jsonc';

/** A D1 database id is a UUID. Anything else is a copy-paste accident. */
export function isDatabaseId(value) {
  return /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/.test(value ?? '');
}

/**
 * The generated file says so, in the one place someone would be looking when
 * they are about to edit it by mistake.
 */
export function render(template, id) {
  if (!template.includes(PLACEHOLDER)) {
    throw new Error(`${TEMPLATE} no longer contains ${PLACEHOLDER} — nothing would be substituted`);
  }
  const header =
    `// GENERATED by \`npm run config\` from ${TEMPLATE}. Do not edit: this file\n` +
    `// is gitignored and is overwritten on every install. Edit ${TEMPLATE}.\n`;
  return header + template.replaceAll(PLACEHOLDER, id);
}

function main() {
  /* The environment wins over `.env`, so CI never has to care whether a stray
     .env exists in the workspace. Node reads the file itself — no dotenv. */
  if (!process.env.D1_DATABASE_ID && existsSync(p('.env'))) process.loadEnvFile(p('.env'));
  const id = process.env.D1_DATABASE_ID?.trim();

  if (!id) {
    /* Deliberately not an error. `npm ci` runs this, and someone who has
       cloned the repository to read it should not be met with a failed
       install. The build is where the absence actually matters, and
       check-content reports it there with the same instructions. */
    console.warn(
      `wrangler-config: D1_DATABASE_ID is not set, so ${OUTPUT} was not written.\n` +
        '  Local:  npx wrangler d1 create portfolio-content\n' +
        '          then put the id it prints in .env as D1_DATABASE_ID, and re-run `npm run config`.\n' +
        '  CI:     set the D1_DATABASE_ID repository secret.\n' +
        '  Reading or typechecking the code needs neither — only dev, build and deploy do.',
    );
    return;
  }

  if (!isDatabaseId(id)) {
    console.error(
      `wrangler-config: D1_DATABASE_ID is not a database id: "${id}"\n` +
        '  Expected a UUID, as printed by `wrangler d1 create` and shown by `wrangler d1 list`.',
    );
    process.exit(1);
  }

  writeFileSync(p(OUTPUT), render(readFileSync(p(TEMPLATE), 'utf8'), id));
  console.log(`wrangler-config: wrote ${OUTPUT}`);
}

function selfTest() {
  const assert = (ok, what) => {
    if (!ok) {
      console.error(`wrangler-config self-test FAILED: ${what}`);
      process.exit(1);
    }
  };
  const id = '285491b7-631b-437b-8d85-b8794b26198c';

  assert(isDatabaseId(id), 'accepts a real database id');
  assert(!isDatabaseId(PLACEHOLDER), 'rejects the placeholder itself');
  assert(!isDatabaseId(''), 'rejects empty');
  assert(!isDatabaseId('portfolio-content'), 'rejects a database name');
  assert(!isDatabaseId(`  ${id}  `), 'rejects untrimmed input');

  const out = render(`{"database_id":"${PLACEHOLDER}"}`, id);
  assert(out.includes(id), 'substitutes the id');
  assert(!out.includes(PLACEHOLDER), 'leaves no placeholder behind');
  assert(out.startsWith('// GENERATED'), 'marks the output as generated');

  let threw = false;
  try { render('{"database_id":"already-real"}', id); } catch { threw = true; }
  assert(threw, 'refuses a template with nothing to substitute');

  /* The template in the repository is the one that actually matters: if it
     stops carrying the placeholder, every generated config silently keeps
     whatever literal was left in its place. */
  assert(readFileSync(p(TEMPLATE), 'utf8').includes(PLACEHOLDER), `${TEMPLATE} carries the placeholder`);

  console.log('wrangler-config self-test: ok');
}

if (process.argv.includes('--self-test')) selfTest();
else main();
